Specs: SpecsCpp::SpecCodeBlock Class Reference
SpecsCpp::SpecCodeBlock Class Reference
#include <SpecCodeBlock.h>
Public Member Functions
SpecCodeBlock (std::unique_ptr< IFunctionPointer< void(ISpecComponent *, ISpec *, SpecCodeBlockAsyncDoneFn *)> > managedBody)
SpecCodeBlock (FunctionPointer< void()> body)
SpecCodeBlock (FunctionPointer< void(SpecDone)> body)
SpecCodeBlock (FunctionPointer< void(ISpec *)> body)
SpecCodeBlock (FunctionPointer< void(ISpecGroup *)> body)
SpecCodeBlock (FunctionPointer< void(ISpecGroup *, SpecDone)> body)
SpecCodeBlock (FunctionPointer< void(ISpec *, SpecDone)> body)
SpecCodeBlock (FunctionPointer< void(ISpecComponent *, ISpec *)> body)
SpecCodeBlock (FunctionPointer< void(ISpecGroup *, ISpec *)> body)
SpecCodeBlock (FunctionPointer< void(ISpecGroup *, ISpecComponent *, ISpec *)> body)
SpecCodeBlock (FunctionPointer< void(ISpecGroup *, ISpec *, SpecDone)> body)
SpecCodeBlock (FunctionPointer< void(ISpecComponent *, ISpec *, SpecDone)> body)
SpecCodeBlock (FunctionPointer< void(ISpecGroup *, ISpecComponent *, ISpec *, SpecDone)> body)
bool is_async () const override
void mark_async (bool async=true) override
std::uint32_t get_timeout_ms () const override
void set_timeout_ms (std::uint32_t timeout_ms) override
SpecCodeBlockBodyFn * body () const override
void set_body (SpecCodeBlockBodyFn *body) override
void run (ISpecComponent *self, ISpecGroup *group, ISpec *spec, ISpecRunResultCallbackFn *resultCallback) override
Public Member Functions inherited from SpecsCpp::ISpecCodeBlock
virtual ~ISpecCodeBlock ()=default
virtual bool is_async () const =0
virtual void mark_async (bool async=true)=0
virtual std::uint32_t get_timeout_ms () const =0
virtual void set_timeout_ms (std::uint32_t timeout_ms)=0
virtual SpecCodeBlockBodyFn * body () const =0
virtual void set_body (SpecCodeBlockBodyFn *)=0
virtual void run (ISpecComponent *, ISpecGroup *, ISpec *, ISpecRunResultCallbackFn *)=0
Additional Inherited Members
Public Types inherited from SpecsCpp::ISpecCodeBlock
using SpecCodeBlockAsyncDoneFn = IFunctionPointer< void()>
using SpecCodeBlockBodyFn = IFunctionPointer< void(ISpecComponent *, ISpec *, SpecCodeBlockAsyncDoneFn *)>
Detailed Description
Definition at line 16 of file SpecCodeBlock.h.
Constructor & Destructor Documentation
SpecCodeBlock() [1/13]
SpecsCpp::SpecCodeBlock::SpecCodeBlock (std::unique_ptr< IFunctionPointer< void(ISpecComponent *, ISpec *, SpecCodeBlockAsyncDoneFn *)> > managedBody) inline
Definition at line 64 of file SpecCodeBlock.h.
            : _managedBody(std::move(managedBody)) {}
SpecCodeBlock() [2/13]
SpecsCpp::SpecCodeBlock::SpecCodeBlock (FunctionPointer< void()> body) inline
Definition at line 69 of file SpecCodeBlock.h.
            : _managedBody(
                  std::make_unique<
                      FunctionPointer<void(ISpecComponent*, ISpec*, SpecCodeBlockAsyncDoneFn*)>>(
                      [body](
                          ISpecComponent* self, ISpec* spec, SpecCodeBlockAsyncDoneFn* asyncDone
                      ) { body.invoke(); }
                  )
              ) {}
SpecCodeBlock() [3/13]
SpecsCpp::SpecCodeBlock::SpecCodeBlock (FunctionPointer< void(SpecDone)> body) inline
Definition at line 79 of file SpecCodeBlock.h.
            : _managedBody(
                  std::make_unique<
                      FunctionPointer<void(ISpecComponent*, ISpec*, SpecCodeBlockAsyncDoneFn*)>>(
                      [body](
                          ISpecComponent* self, ISpec* spec, SpecCodeBlockAsyncDoneFn* asyncDone
                      ) { body.invoke(SpecDone{asyncDone}); }
                  )
              ) {
            mark_async();
        }
SpecCodeBlock() [4/13]
SpecsCpp::SpecCodeBlock::SpecCodeBlock (FunctionPointer< void(ISpec *)> body) inline
Definition at line 91 of file SpecCodeBlock.h.
            : _managedBody(
                  std::make_unique<
                      FunctionPointer<void(ISpecComponent*, ISpec*, SpecCodeBlockAsyncDoneFn*)>>(
                      [body](
                          ISpecComponent* self, ISpec* spec, SpecCodeBlockAsyncDoneFn* asyncDone
                      ) { body.invoke(spec); }
                  )
              ) {}
SpecCodeBlock() [5/13]
SpecsCpp::SpecCodeBlock::SpecCodeBlock (FunctionPointer< void(ISpecGroup *)> body) inline
Definition at line 101 of file SpecCodeBlock.h.
            : _managedBody(std::make_unique<FunctionPointer<
                               void(ISpecComponent*, ISpec*, SpecCodeBlockAsyncDoneFn*)>>(
                  [body](ISpecComponent* self, ISpec* spec, SpecCodeBlockAsyncDoneFn* asyncDone) {
                      // If 'self' is a group, invoke the body with it, otherwise invoke with the
                      // group() of self, if any
                      if (auto* group = dynamic_cast<ISpecGroup*>(self)) body.invoke(group);
                      else if (auto* group = self->group()) _Log_("AFTER");
                      ;
                  }
              )) {}
SpecCodeBlock() [6/13]
SpecsCpp::SpecCodeBlock::SpecCodeBlock (FunctionPointer< void(ISpecGroup *, SpecDone)> body) inline
Definition at line 113 of file SpecCodeBlock.h.
            : _managedBody(
                  std::make_unique<
                      FunctionPointer<void(ISpecComponent*, ISpec*, SpecCodeBlockAsyncDoneFn*)>>(
                      [body](
                          ISpecComponent* self, ISpec* spec, SpecCodeBlockAsyncDoneFn* asyncDone
                      ) { body.invoke(self->group(), SpecDone{asyncDone}); }
                  )
              ) {
            mark_async();
        }
SpecCodeBlock() [7/13]
SpecsCpp::SpecCodeBlock::SpecCodeBlock (FunctionPointer< void(ISpec *, SpecDone)> body) inline
Definition at line 125 of file SpecCodeBlock.h.
            : _managedBody(
                  std::make_unique<
                      FunctionPointer<void(ISpecComponent*, ISpec*, SpecCodeBlockAsyncDoneFn*)>>(
                      [body](
                          ISpecComponent* self, ISpec* spec, SpecCodeBlockAsyncDoneFn* asyncDone
                      ) { body.invoke(spec, SpecDone{asyncDone}); }
                  )
              ) {
            mark_async();
        }
SpecCodeBlock() [8/13]
SpecsCpp::SpecCodeBlock::SpecCodeBlock (FunctionPointer< void(ISpecComponent *, ISpec *)> body) inline
Definition at line 137 of file SpecCodeBlock.h.
            : _managedBody(
                  std::make_unique<
                      FunctionPointer<void(ISpecComponent*, ISpec*, SpecCodeBlockAsyncDoneFn*)>>(
                      [body](
                          ISpecComponent* self, ISpec* spec, SpecCodeBlockAsyncDoneFn* asyncDone
                      ) { body.invoke(self, spec); }
                  )
              ) {}
SpecCodeBlock() [9/13]
SpecsCpp::SpecCodeBlock::SpecCodeBlock (FunctionPointer< void(ISpecGroup *, ISpec *)> body) inline
Definition at line 147 of file SpecCodeBlock.h.
            : _managedBody(
                  std::make_unique<
                      FunctionPointer<void(ISpecComponent*, ISpec*, SpecCodeBlockAsyncDoneFn*)>>(
                      [body](
                          ISpecComponent* self, ISpec* spec, SpecCodeBlockAsyncDoneFn* asyncDone
                      ) { body.invoke(self->group(), spec); }
                  )
              ) {}
SpecCodeBlock() [10/13]
SpecsCpp::SpecCodeBlock::SpecCodeBlock (FunctionPointer< void(ISpecGroup *, ISpecComponent *, ISpec *)> body) inline
Definition at line 157 of file SpecCodeBlock.h.
            : _managedBody(
                  std::make_unique<
                      FunctionPointer<void(ISpecComponent*, ISpec*, SpecCodeBlockAsyncDoneFn*)>>(
                      [body](
                          ISpecComponent* self, ISpec* spec, SpecCodeBlockAsyncDoneFn* asyncDone
                      ) { body.invoke(self->group(), self, spec); }
                  )
              ) {}
SpecCodeBlock() [11/13]
SpecsCpp::SpecCodeBlock::SpecCodeBlock (FunctionPointer< void(ISpecGroup *, ISpec *, SpecDone)> body) inline
Definition at line 167 of file SpecCodeBlock.h.
            : _managedBody(
                  std::make_unique<
                      FunctionPointer<void(ISpecComponent*, ISpec*, SpecCodeBlockAsyncDoneFn*)>>(
                      [body](
                          ISpecComponent* self, ISpec* spec, SpecCodeBlockAsyncDoneFn* asyncDone
                      ) { body.invoke(self->group(), spec, SpecDone{asyncDone}); }
                  )
              ) {
            mark_async();
        }
SpecCodeBlock() [12/13]
SpecsCpp::SpecCodeBlock::SpecCodeBlock (FunctionPointer< void(ISpecComponent *, ISpec *, SpecDone)> body) inline
Definition at line 179 of file SpecCodeBlock.h.
            : _managedBody(
                  std::make_unique<
                      FunctionPointer<void(ISpecComponent*, ISpec*, SpecCodeBlockAsyncDoneFn*)>>(
                      [body](
                          ISpecComponent* self, ISpec* spec, SpecCodeBlockAsyncDoneFn* asyncDone
                      ) { body.invoke(self, spec, SpecDone{asyncDone}); }
                  )
              ) {
            mark_async();
        }
SpecCodeBlock() [13/13]
SpecsCpp::SpecCodeBlock::SpecCodeBlock (FunctionPointer< void(ISpecGroup *, ISpecComponent *, ISpec *, SpecDone)> body) inline
Definition at line 191 of file SpecCodeBlock.h.
            : _managedBody(
                  std::make_unique<
                      FunctionPointer<void(ISpecComponent*, ISpec*, SpecCodeBlockAsyncDoneFn*)>>(
                      [body](
                          ISpecComponent* self, ISpec* spec, SpecCodeBlockAsyncDoneFn* asyncDone
                      ) { body.invoke(self->group(), self, spec, SpecDone{asyncDone}); }
                  )
              ) {
            mark_async();
        }
Member Function Documentation
body()
SpecCodeBlockBodyFn * SpecsCpp::SpecCodeBlock::body () const inline override virtual
Implements SpecsCpp::ISpecCodeBlock.
Definition at line 209 of file SpecCodeBlock.h.
{
            return _unmanagedBody ? _unmanagedBody : _managedBody.get();
        }
Referenced by run(), set_body(), SpecCodeBlock(), SpecCodeBlock(), SpecCodeBlock(), SpecCodeBlock(), SpecCodeBlock(), SpecCodeBlock(), SpecCodeBlock(), SpecCodeBlock(), SpecCodeBlock(), SpecCodeBlock(), SpecCodeBlock(), and SpecCodeBlock().
get_timeout_ms()
std::uint32_t SpecsCpp::SpecCodeBlock::get_timeout_ms () const inline override virtual
Implements SpecsCpp::ISpecCodeBlock.
Definition at line 206 of file SpecCodeBlock.h.
{ return _timeout_ms; }
Referenced by run().
is_async()
bool SpecsCpp::SpecCodeBlock::is_async () const inline override virtual
Implements SpecsCpp::ISpecCodeBlock.
Definition at line 203 of file SpecCodeBlock.h.
{ return _async; }
Referenced by run().
mark_async()
void SpecsCpp::SpecCodeBlock::mark_async (bool async = true) inline override virtual
Implements SpecsCpp::ISpecCodeBlock.
Definition at line 204 of file SpecCodeBlock.h.
{ _async = async; }
run()
void SpecsCpp::SpecCodeBlock::run (ISpecComponent * self, ISpecGroup * group, ISpec * spec, ISpecRunResultCallbackFn * resultCallback) inline override virtual
Implements SpecsCpp::ISpecCodeBlock.
Definition at line 215 of file SpecCodeBlock.h.
                   {
            try {
                if (is_async()) {
                    _asyncDonePromise = std::make_unique<std::promise<void>>();
                    body()->invoke(self, spec, &_markAsyncPromiseDoneFn);
                    auto asyncDoneFuture = _asyncDonePromise->get_future();
                    if (get_timeout_ms() > 0) {
                        if (asyncDoneFuture.wait_for(std::chrono::milliseconds(get_timeout_ms())) ==
                            std::future_status::timeout) {
                            if (resultCallback) {
                                auto result = SpecRunResult::timeout(self, group, spec);
                                resultCallback->invoke(result.get());
                                return;
                            } else {
                                _Log_("Code block timed out");
                            }
                        }
                    }
                    asyncDoneFuture.get();
                } else {
                    body()->invoke(self, spec, nullptr);
                }
                if (!resultCallback) return;
                auto result = SpecRunResult::passed(self, group, spec);
                resultCallback->invoke(result.get());
            } catch (...) {
                _exceptionHandled = false;
                // ...
                if (_asyncDonePromise) _asyncDonePromise->set_exception(std::current_exception());
                if (auto* currentlyRunningSpecEnvironment = global_spec_environment().get()) {
                    if (auto* exceptionHandlers =
                            currentlyRunningSpecEnvironment->local_exception_handlers()) {
                        _currentExceptionMessage.clear();
                        _currentExceptionPtr =
                            std::make_unique<std::exception_ptr>(std::current_exception());
                        exceptionHandlers->foreach_exception_handler(&_forEachExceptionHandlerFn);
                        if (_exceptionHandled) {
                            if (resultCallback) {
                                auto result = SpecRunResult::failed(
                                    self, group, spec, _currentExceptionMessage.c_str()
                                );
                                resultCallback->invoke(result.get());
                            } else {
                                _Log_("Code block error: {}", _currentExceptionMessage);
                            }
                        } else {
                            if (resultCallback) {
                                auto result =
                                    SpecRunResult::failed(self, group, spec, "Unknown exception");
                                resultCallback->invoke(result.get());
                            } else {
                                _Log_("Code block error: Unhandled exception");
                            }
                        }
                    } else {
                        _Log_("No exception handlers registered");
                    }
                } else {
                    _Log_("No currently running spec environment");
                }
            }
        }
set_body()
void SpecsCpp::SpecCodeBlock::set_body (SpecCodeBlockBodyFn * body) inline override virtual
Implements SpecsCpp::ISpecCodeBlock.
Definition at line 213 of file SpecCodeBlock.h.
{ _unmanagedBody = body; }
set_timeout_ms()
void SpecsCpp::SpecCodeBlock::set_timeout_ms (std::uint32_t timeout_ms) inline override virtual
Implements SpecsCpp::ISpecCodeBlock.
Definition at line 207 of file SpecCodeBlock.h.
{ _timeout_ms = timeout_ms; }
The documentation for this class was generated from the following file:
Specs.Implementations/include/Specs/SpecCodeBlock.h