Specs: SpecsCpp::ISpecDataValueCollection Struct Reference
SpecsCpp::ISpecDataValueCollection Struct Reference abstract
#include <API.h>
Public Types
using ForEachSpecDataFn = IFunctionPointer< void(ISpecDataValue *)>
Public Member Functions
virtual ~ISpecDataValueCollection ()=default
virtual void add (ISpecDataValue *)=0
virtual bool has (const char *name) const =0
virtual ISpecDataValue * get (const char *name) const =0
virtual bool get_bool (const char *name) const
virtual int get_int (const char *name) const
virtual unsigned int get_unsigned_int (const char *name) const
virtual double get_float (const char *name) const
virtual const char * get_string (const char *name) const
virtual void * get_pointer (const char *name) const
virtual void foreach_value (ForEachSpecDataFn *) const =0
virtual void merge (ISpecDataValueCollection *)=0
virtual void clear ()=0
void foreach (std::function< void(ISpecDataValue *)> fn) const
Detailed Description
Definition at line 67 of file API.h.
Member Typedef Documentation
ForEachSpecDataFn
using SpecsCpp::ISpecDataValueCollection::ForEachSpecDataFn = IFunctionPointer<void(ISpecDataValue*)>
Definition at line 68 of file API.h.
Constructor & Destructor Documentation
~ISpecDataValueCollection()
virtual SpecsCpp::ISpecDataValueCollection::~ISpecDataValueCollection () virtual default
Member Function Documentation
add()
virtual void SpecsCpp::ISpecDataValueCollection::add (ISpecDataValue *) pure virtual
Implemented in SpecsCpp::SpecDataValueCollection.
clear()
virtual void SpecsCpp::ISpecDataValueCollection::clear () pure virtual
Implemented in SpecsCpp::SpecDataValueCollection.
foreach()
void SpecsCpp::ISpecDataValueCollection::foreach (std::function< void(ISpecDataValue *)> fn) const inline
Definition at line 105 of file API.h.
{
            auto callback = unique_function_pointer(fn);
            this->foreach_value(callback.get());
        }
foreach_value()
virtual void SpecsCpp::ISpecDataValueCollection::foreach_value (ForEachSpecDataFn *) const pure virtual
Implemented in SpecsCpp::SpecDataValueCollection.
Referenced by foreach(), and SpecsCpp::SpecDataValueCollection::merge().
get()
virtual ISpecDataValue * SpecsCpp::ISpecDataValueCollection::get (const char * name) const pure virtual
Implemented in SpecsCpp::SpecDataValueCollection.
Referenced by get_bool(), get_float(), get_int(), get_pointer(), get_string(), and get_unsigned_int().
get_bool()
virtual bool SpecsCpp::ISpecDataValueCollection::get_bool (const char * name) const inline virtual
Definition at line 76 of file API.h.
{
            if (!has(name)) return false;
            return get(name)->bool_value();
        }
get_float()
virtual double SpecsCpp::ISpecDataValueCollection::get_float (const char * name) const inline virtual
Definition at line 88 of file API.h.
{
            if (!has(name)) return 0.0;
            return get(name)->float_value();
        }
get_int()
virtual int SpecsCpp::ISpecDataValueCollection::get_int (const char * name) const inline virtual
Definition at line 80 of file API.h.
{
            if (!has(name)) return 0;
            return get(name)->int_value();
        }
get_pointer()
virtual void * SpecsCpp::ISpecDataValueCollection::get_pointer (const char * name) const inline virtual
Definition at line 96 of file API.h.
{
            if (!has(name)) return nullptr;
            return get(name)->pointer_value();
        }
get_string()
virtual const char * SpecsCpp::ISpecDataValueCollection::get_string (const char * name) const inline virtual
Definition at line 92 of file API.h.
{
            if (!has(name)) return nullptr;
            return get(name)->string_value();
        }
get_unsigned_int()
virtual unsigned int SpecsCpp::ISpecDataValueCollection::get_unsigned_int (const char * name) const inline virtual
Definition at line 84 of file API.h.
{
            if (!has(name)) return 0;
            return get(name)->unsigned_int_value();
        }
has()
virtual bool SpecsCpp::ISpecDataValueCollection::has (const char * name) const pure virtual
Implemented in SpecsCpp::SpecDataValueCollection.
Referenced by get_bool(), get_float(), get_int(), get_pointer(), get_string(), and get_unsigned_int().
merge()
virtual void SpecsCpp::ISpecDataValueCollection::merge (ISpecDataValueCollection *) pure virtual
Implemented in SpecsCpp::SpecDataValueCollection.
The documentation for this struct was generated from the following file:
Specs.API/include/Specs/API/Internal/Undocumented/API.h