Specs: SpecsCpp::ISpecEnvironment Struct Reference
SpecsCpp::ISpecEnvironment Struct Reference abstract
#include <API.h>
Public Member Functions
virtual ~ISpecEnvironment ()=default
virtual ISpecOutput * standard_output () const =0
virtual void set_standard_output (ISpecOutput *)=0
virtual ISpecOutput * error_output () const =0
virtual void set_error_output (ISpecOutput *)=0
virtual ISpecGroup * root_group () const =0
virtual ILocalSpecExceptionHandlerCollection * local_exception_handlers () const =0
virtual ISpecRunnerCollection * runners () const =0
virtual ISpecReporterCollection * reporters () const =0
virtual void run (ISpecRunner *, ISpecReporterCollection *, ISpecRunOptions *, ISpecSuiteRunResultCallbackFn *)=0
Detailed Description
Definition at line 509 of file API.h.
Constructor & Destructor Documentation
~ISpecEnvironment()
virtual SpecsCpp::ISpecEnvironment::~ISpecEnvironment () virtual default
Member Function Documentation
error_output()
virtual ISpecOutput * SpecsCpp::ISpecEnvironment::error_output () const pure virtual
Implemented in SpecsCpp::SpecEnvironment.
local_exception_handlers()
virtual ILocalSpecExceptionHandlerCollection * SpecsCpp::ISpecEnvironment::local_exception_handlers () const pure virtual
Implemented in SpecsCpp::SpecEnvironment.
Referenced by SpecsCpp::register_exception_handler().
reporters()
virtual ISpecReporterCollection * SpecsCpp::ISpecEnvironment::reporters () const pure virtual
Implemented in SpecsCpp::SpecEnvironment.
Referenced by SpecsCpp::register_reporter().
root_group()
virtual ISpecGroup * SpecsCpp::ISpecEnvironment::root_group () const pure virtual
Implemented in SpecsCpp::SpecEnvironment.
run()
virtual void SpecsCpp::ISpecEnvironment::run (ISpecRunner * , ISpecReporterCollection * , ISpecRunOptions * , ISpecSuiteRunResultCallbackFn *) pure virtual
Implemented in SpecsCpp::SpecEnvironment.
runners()
virtual ISpecRunnerCollection * SpecsCpp::ISpecEnvironment::runners () const pure virtual
Implemented in SpecsCpp::SpecEnvironment.
Referenced by SpecsCpp::register_runner().
set_error_output()
virtual void SpecsCpp::ISpecEnvironment::set_error_output (ISpecOutput *) pure virtual
Implemented in SpecsCpp::SpecEnvironment.
set_standard_output()
virtual void SpecsCpp::ISpecEnvironment::set_standard_output (ISpecOutput *) pure virtual
Implemented in SpecsCpp::SpecEnvironment.
standard_output()
virtual ISpecOutput * SpecsCpp::ISpecEnvironment::standard_output () const pure virtual
Implemented in SpecsCpp::SpecEnvironment.
The documentation for this struct was generated from the following file:
Specs.API/include/Specs/API/Internal/Undocumented/API.h